version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1416
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      BOT_TOKEN: "7849932150:AAFu0PFxUvV5Lyiaibya9OERwVxFi3YTqSI"
      BOT_USERNAME: "yulduzmavlyanova_bot"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/bot"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1416"
      ADMIN_CHAT_ID: "7001780741"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
